name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 20x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm dependencies
      run: npm install
    - name: Start the backend
      run: npm start &
    - run: npm run server &
    - run: npx playwright install
    - name: Start the tests
      run: npm test
    
  deploy-backend:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
    - name: Deploy to production
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.BACKEND_KEY }}
        api-key: ${{ secrets.RENDER_KEY }}
    - name: Sleep for 60 seconds
      run: sleep 60

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend
    steps:
    - name: Deploy to production
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.FRONTEND_KEY }}
        api-key: ${{ secrets.RENDER_KEY }}
    - name: Sleep for 60 seconds
      run: sleep 60
